use std::sync::Arc;
use std::time::Duration;

use serde::{Deserialize, Serialize};
use tokio::sync::mpsc;
use tokio::task::JoinHandle;

use crate::error::NervaError;

/// A suggestion generated by a watcher.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Suggestion {
    /// Which watcher generated this suggestion.
    pub source: String,
    /// Short summary for display (e.g., notification title).
    pub title: String,
    /// Detailed text.
    pub body: String,
    /// Optional tool to invoke if the user accepts.
    pub action: Option<SuggestedAction>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SuggestedAction {
    pub tool_id: String,
    pub input: serde_json::Value,
}

/// Trait for implementing watchers that monitor state and emit suggestions.
#[async_trait::async_trait]
pub trait Watcher: Send + Sync {
    /// Unique identifier for this watcher.
    fn id(&self) -> &str;

    /// How often to poll (watchers are polling-based).
    fn interval(&self) -> Duration;

    /// Check for state changes and return suggestions, if any.
    async fn poll(&self) -> Result<Vec<Suggestion>, NervaError>;
}

/// Manages multiple watchers, running them on their own poll intervals.
pub struct WatcherManager {
    tx: mpsc::Sender<Suggestion>,
    rx: mpsc::Receiver<Suggestion>,
    handles: Vec<(String, JoinHandle<()>)>,
}

impl WatcherManager {
    pub fn new(buffer: usize) -> Self {
        let (tx, rx) = mpsc::channel(buffer);
        Self {
            tx,
            rx,
            handles: Vec::new(),
        }
    }

    /// Register and start a watcher.
    pub fn register(&mut self, watcher: Arc<dyn Watcher>) {
        let id = watcher.id().to_string();
        let tx = self.tx.clone();
        let interval = watcher.interval();

        let id_for_task = id.clone();
        let handle = tokio::spawn(async move {
            let id = id_for_task;
            let mut ticker = tokio::time::interval(interval);
            loop {
                ticker.tick().await;
                match watcher.poll().await {
                    Ok(suggestions) => {
                        for suggestion in suggestions {
                            if tx.send(suggestion).await.is_err() {
                                tracing::debug!("Watcher channel closed, stopping");
                                return;
                            }
                        }
                    }
                    Err(e) => {
                        tracing::debug!(watcher = %id, error = %e, "Watcher poll error");
                    }
                }
            }
        });

        tracing::info!(watcher = %id, interval_ms = interval.as_millis(), "Watcher registered");
        self.handles.push((id, handle));
    }

    /// Receive the next suggestion (blocking).
    pub async fn next_suggestion(&mut self) -> Option<Suggestion> {
        self.rx.recv().await
    }

    /// Stop all watchers.
    pub fn stop_all(&mut self) {
        for (id, handle) in self.handles.drain(..) {
            tracing::info!(watcher = %id, "Stopping watcher");
            handle.abort();
        }
    }

    /// Number of registered watchers.
    pub fn count(&self) -> usize {
        self.handles.len()
    }
}

impl Drop for WatcherManager {
    fn drop(&mut self) {
        self.stop_all();
    }
}
